### PR TITLE
Revert "add line feed for RCUTILS_SAFE_FWRITE_TO_STDERR (#608)"

### PR DESCRIPTION
**Pull request by fujitatomoya**
This reverts commit 7202ceb7e379ec0fbcaf895cfcef6983ddcc7077.

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@Blast545 can you check this revert just in case?

**Review by Blast545 — APPROVED** [review]
Revert looks good to me

**Comment by Blast545** [comment]
@fujitatomoya FYI This test regression is affecting only one rmw, and it's tier 2 for ROS2 Humble. A revert is not mandatory for this one if you are going to be taking a look into it.

**Comment by fujitatomoya** [comment]
@Blast545 thanks for checking.

**Pull request merged**
