### PR TITLE
Use empty() instead of size() to check if a vector/map contains eleme…

### PR DESCRIPTION
**Pull request by jwillemsen**
…nts and fixed some incorrect logging

    * rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp:
    * rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/topic_cache.hpp:
    * rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp:
    * rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp:
    * rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp:
    * rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp:

### CODE REVIEW

**Comment by jwillemsen** [comment]
Found when working on rmw_opendds (see https://github.com/jwillemsen/rmw_opendds/tree/jwi-openddsros2)

**Comment by tfoote** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5888/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2436/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4881/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5789/)

**Comment by jwillemsen** [comment]
Windows failure seems to be a problem with the git checkout

<pre>
04:49:40 === src\ros2/rmw_fastrtps (git) ===
04:49:40 Invocation of command 'import' on client 'git' failed: PermissionError: [WinError 5] Access is denied: 'src\\ros2/rmw_fastrtps' (c:\python37\lib\site-packages\vcstool\clients\git.py:209)
04:49:40 <== 'vcs import "src" --force --retry 5 --input 01-rmwf.repos' exited with return code '1'
04:49:40 
</pre>

**Comment by tfoote** [comment]
Yeah, I used the supplimentary repos file and I've seen the same issue with windows failing to checkout using that. We're past the freeze date for the crystal release so since this is an optimization we're going to target these to land after the release.

**Comment by jwillemsen** [comment]
Ok, probably more PRs will be coming from my side, trying to create a new rmw_opendds to provide OpenDDS as alternative DDS implementation

**Comment by tfoote** [comment]
That's great we're happy to have more implementations available.

**Comment by sloretz** [comment]
CI (fastrtps static/dynamic packages up to test_communication)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5937/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2463/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4907/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5827/)

**Comment by sloretz** [comment]
Thanks for the PR!

Since OSX ci has a long wait this passed on OSX before, I'll merge this and cancel the OSX job I started.

**Pull request merged**
