### PR TITLE
Unify and simplify de/serializeROSmessage processing

### PR DESCRIPTION
**Pull request by jwang11**
For most type_id, there is no difference for serialization which can be unified in a common template function. However, for bool and string, there is extra check or logic for normal but array does not. Although it is weird, this commit keep the logic intact.

Signed-off-by: jwang <jing.j.wang@intel.com>

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
This is a follow up of https://github.com/ros2/rmw_fastrtps/pull/168 now that most of the logic for array has been simplified and magic numbers removed.

Thanks @jwang11 we'll try to get this reviewed soon

**Comment by mikaelarguedas** [comment]
> Although it is weird, this commit keep the logic intact.

Yes this extra logic is necessary, thanks for keeping it as is.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3415/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/659/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2742/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3459/)

**Comment by mikaelarguedas** [comment]
While it's counter intuitive to call (de)serializeArray for non array types I appreciate the code deduplication.

I'll leave a chance to @ros2/team to voice any concern before merging

**Comment by dirk-thomas** [comment]
Before the code was calling the following for non-array fields:

```
ser << *static_cast<uint8_t *>(field);
```

With the patch it is calling this line instead:

```
ser.serializeArray(static_cast<uint8_t *>(field), 1);
```

I don't think we can rely on them being equivalent without making assumptions about how `serializeArray` is implemented. And that could change anytime. Therefore this change doesn't look like a good idea to me.

**Comment by jwang11** [comment]
```
ser.serializeArray(static_cast<uint8_t *>(field), 1);
```
Ok, If it introduce the dependency on specific FastRTPS implementation, I can update the commit to handle non-array type separately, but still in same function.

**Comment by jwang11** [comment]
Code updated. Separate the process for single field and array according to comments, consolidate them in central function which obviously help code deduplication.

**Comment by dirk-thomas** [comment]
Thank you for improving the code.

**Pull request merged**
