### PR TITLE
Rename *_commons -> *_common

### PR DESCRIPTION
**Pull request by dhood**
connects to ros2/rmw_connext#240

thanks for indulging me

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/389/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2354/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3033/)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The file `rmw_fastrtps_cpp/src/type_support_common.hpp` is new in this PR. Shouldn't the existing file be renamed instead?

**Comment by mikaelarguedas** [comment]
looks like type_support_common.hpp has been copied and not renamed resulting in the files to be duplicated

**Comment by dhood** [comment]
that diff looks better now! https://github.com/ros2/rmw_fastrtps/pull/136/commits/c3276ffc028a8d209248c4ba5c54216473423bd4

CI w/ fastrtps only
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2912/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/390/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2355/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3034/)

**Comment by mikaelarguedas** [comment]
hmmm did portable lose it's git credentials ?

**Comment by mikaelarguedas** [comment]
Portable is back online with restored git credentials
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3036/)

**Pull request merged**
