### PR TITLE
use auto deduction and nullptr to keep coding style consistent

### PR DESCRIPTION
**Pull request by jwang11**
This commit use auto to deduce complex TYPE and replace NULL with nullptr. It
helps to keep coding style consistent across the project

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks @jwang11, we never took time of homogenizing the style since we took ownership of this repo. Appreciated.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3372/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/623/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2705/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3425/)

**Comment by dirk-thomas** [comment]
`auto` makes the code shorter in many cases without reducing the readability, e.g.:

```
auto impl = static_cast<CustomClientInfo *>(client->data);
```

But in some cases I think it would be beneficial to keep the specific type since `auto` "removes" some of the information, e.g.;

```
rcutils_ret_t ret = _assign_partitions_to_attributes(...);
```

**Comment by mikaelarguedas** [comment]
> But in some cases I think it would be beneficial to keep the specific type since auto "removes" some of the information, e.g.;
>```
>rcutils_ret_t ret = _assign_partitions_to_attributes(...);
>```

That's a fair point. When reviewing I considered it ok if the information could be extracted from the next line easily. But I think you're right, people not familiar with the codebase should be able to have all the context by reading only the line in question without having to check what other functions return or knowing that an `RMW_RET_OK` is an enum of type `rmw_ret_t`. 
@jwang11 would you mind reducing the scope to use auto only for the cases where readibility is not impacted?

**Comment by jwang11** [comment]
yes, I agree auto usage should not impact readability an actually I have kept some std::xxx type there. I'll double check the commit.

**Comment by jwang11** [comment]
conflict is resolved, please continue review

**Comment by mikaelarguedas** [comment]
Baased on previous comments, it would be good to reduce the scope of this and not use auto for return codes types and `const rosidl_message_type_support_t *` that are not trivial to deduce from the line itself

**Comment by jwang11** [comment]
For "const rosidl_message_type_support_t *" , it really should be kept, but
Return code type can be easily reduced from next line, do you think it impact readability?
  auto ret = rmw_names_and_types_check_zero(topic_names_and_types);
  if (ret != RMW_RET_OK)

**Comment by mikaelarguedas** [comment]
We don't really have a policy for this, I think the conclusion from the previous discussion is that the line itself should provide enough context to know what the returned type is. I would be fine having auto if the next line provides the context but also understand the reasoning that a single line should be enough to have all the information, maybe @ros2/team wants to pitch in on this

**Comment by dirk-thomas** [comment]
From my point of view using `auto ret` is problematic because the following line `if (ret != RMW_RET_OK)` could either be correct (since `ret` is of type `rmw_ret_t`) or it could be wrong (if `ret` would be of type `rcl_ret_t`). And since that is not obvious anymore I would like to keep the strong explicit typing on that kind of variables.

**Comment by clalancette** [comment]
I agree with @dirk-thomas on this; I'd prefer to be more explicit on the return variables.

**Comment by jwang11** [comment]
So, sounds reasonable to keep explicit return variable. I am fine to update the commit.

**Comment by mikaelarguedas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3395/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/640/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3442/)

**Pull request merged**
