### PR TITLE
Fastrtps 1.7.0

### PR DESCRIPTION
**Pull request by MiguelCompany**
We are preparing a new release of Fast-RTPS (see eProsima/Fast-RTPS#304).

A small change is required on rmw_fastrtps_shared_cpp so it can compile against the new release.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
In the current state (using this branch as well as the FastRTPS branch) CI fails on all platforms:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5497/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2166/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4538/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5400/)

```
CMake Error at CMakeLists.txt:40 (add_library):
  Target "rmw_fastrtps_shared_cpp" links to target "OpenSSL::SSL" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:40 (add_library):
  Target "rmw_fastrtps_shared_cpp" links to target "OpenSSL::Crypto" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

**Comment by MiguelCompany** [comment]
Hi @dirk-thomas 

We finally have eProsima/Fast-RTPS#304 ready to be merged. I have passed the tests locally without problems.

So please test and review this PR.

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5608/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2239/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4621/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5487/)

**Comment by dirk-thomas** [comment]
The PR build is expected to fail since it doesn't know about the custom branch in the `eProsima/Fast-RTPS` repo.

**Comment by dirk-thomas** [comment]
The Linux builds look good. The clang warnings on macOS should be easy to address in this PR. On Windows it seems that there is some kind of regression which makes a whole group of tests fail.

**Comment by MiguelCompany** [comment]
@dirk-thomas Looking at the report, I've seen that the Windows build is the only one with `isolated:false`. Could that make a difference?

**Comment by MiguelCompany** [comment]
I also see that the issues are in the communication with rmw_connext, so I cannot check it locally. We check with shapes_demo and all seems ok.

**Comment by dirk-thomas** [comment]
> Looking at the report, I've seen that the Windows build is the only one with `isolated:false`. Could that make a difference?

No, that is always the case and without this patch these tests pass. With isolation the environment variables in such a large workspace simply get too long on Windows.

> I also see that the issues are in the communication with rmw_connext, so I cannot check it locally. We check with shapes_demo and all seems ok.

The shapes demo only tests a very small subset and is therefore not a sufficient test. Please do test it with Connext locally. I am not sure why you say "I cannot check it locally". You can use the provided Debian package of Connext to build the current state with FastRTPS and Connext to run the tests in question locally (see https://index.ros.org/doc/ros2/Linux-Development-Setup/#debian-packages-provided-in-the-ros-2-apt-repositories).

**Comment by MiguelCompany** [comment]
> Also the `rmw_fastrtps_dynamic_cpp` implementation seems to have a problem with a specific message type (DynamicArrayStaticArrayPrimitivesNested) on Linux: https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/176/#showFailuresLink

That is a nightly run on master, so it is not related with this PR.

**Comment by dirk-thomas** [comment]
> That is a nightly run on master, so it is not related with this PR.

That is correct. The problem already exists on master. I just wanted to point out that it would be good to address that problem before considering to tag a version of FastRTPS.

**Comment by MiguelCompany** [comment]
> > That is a nightly run on master, so it is not related with this PR.
> 
> That is correct. The problem already exists on master. I just wanted to point out that it would be good to address that problem before considering to tag a version of FastRTPS.

I have checked and it has been failing since October 26th (https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/147/#showFailuresLink). That day it also failed on rmw_fastrtps_cpp and rmw_opensplice_cpp. No changes were done on Fast-RTPS on that date, so I guess it should be something related with the introspection typesupport (or on rmw_fastrtps_dynamic_cpp itself)

**Comment by dirk-thomas** [comment]
Indeed, I think `rmw_fastrtps_dynamic_cpp` is the most likely suspect. I would just encourage you to try to debug the problem and attempt to fix it.

**Comment by MiguelCompany** [comment]
Hi @dirk-thomas 

We addressed the communication issues with connext on the release branch of Fast-RTPS, so this PR should pass the tests now.

For the issues with rmw_fastrtps_dynamic_cpp, see #242

**Comment by dirk-thomas** [comment]
* Windows [Build Status](https://ci.ros2.org/job/ci_windows/5551/)

There are two warning remaining: https://ci.ros2.org/job/ci_windows/5551/warnings43Result/new/

**Comment by dirk-thomas** [comment]
@MiguelCompany can you briefly comment here to confirm that you have received the notification and are working on fixing the remaining warnings?

**Comment by MiguelCompany** [comment]
@dirk-thomas Yes, I have received the notification. The warnings were solved on eProsima/Fast-RTPS#338
We are now solving eProsima/Fast-RTPS#250 with eProsima/Fast-RTPS#341, which should be ready today.

**Comment by MiguelCompany** [comment]
Hey @dirk-thomas 

We have just merged eProsima/Fast-RTPS#341 and are adding some regression tests on eProsima/Fast-RTPS#342.

We don't plan any additional change for release 1.7.0, and would like to merge it to master on Monday.

Please run CI on this PR and proceed with the review.

**Comment by dirk-thomas** [comment]
Due to recent merges to the master branch this needs to be rebased in order to run CI.

**Comment by dirk-thomas** [comment]
> Due to recent merges to the master branch this needs to be rebased in order to run CI.

@MiguelCompany can you please do this today so that we can run CI and confirm that there are no surprises on Monday.

**Comment by MiguelCompany** [comment]
> > Due to recent merges to the master branch this needs to be rebased in order to run CI.
> 
> @MiguelCompany can you please do this today so that we can run CI and confirm that there are no surprises on Monday.

@dirk-thomas As there were no conflicts with master, I have done the rebase directly. As I am at home now, I couldn't check locally.

**Comment by dirk-thomas** [comment]
> We don't plan any additional change for release 1.7.0, and would like to merge it to master on Monday.

@MiguelCompany any update on this?

**Comment by MiguelCompany** [comment]
Hi @dirk-thomas 

We were polishing the user docs before releasing. We will do it today 16:30 CET (7:30 PST). Thanks for your support with this PR.

**Comment by richiware** [comment]
@dirk-thomas We've fixed a bug when using network interfaces whitelist. This doesn't affect the common use of fastrtps, but to be sure, can you test last status of release-1.7.0? Thanks

**Comment by dirk-thomas** [comment]
> to be sure, can you test last status of release-1.7.0?

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5783/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2359/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4779/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5679/)

**Comment by richiware** [comment]
@dirk-thomas Thanks a lot. We will merge v1.7.0 on our master branch.

**Comment by richiware** [comment]
@dirk-thomas FYI. Merge done in Fast-RTPS

**Comment by dirk-thomas** [comment]
The nightly job building `Debug` on Windows has one new warning: https://ci.ros2.org/view/nightly/job/nightly_win_deb/1085/warnings43Result/new/

**Pull request merged**
