### PR TITLE
Change default to synchronous

### PR DESCRIPTION
**Pull request by audrow**
@JaimeMartin and @MiguelCompany, is this the right way to make synchronous the default?

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]
The README should also be updated to indicate that the default publishing mode is SYNCHRONOUS.

Also the code block starting at [line 209](https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_shared_cpp/src/participant.cpp#L209) which reads the `RMW_FASTRTPS_PUBLICATION_MODE` should also be updated accordingly.

```suggestion
    if (env_value != nullptr) {
      // Asynchronous publishing
      if (strcmp(env_value, "ASYNCHRONOUS") == 0) {
        publishing_mode = publishing_mode_t::ASYNCHRONOUS;
      } else if (strcmp(env_value, "AUTO") == 0) {
        publishing_mode = publishing_mode_t::AUTO;
      } else if (strcmp(env_value, "SYNCHRONOUS") != 0 && strcmp(env_value, "") != 0) {
        RCUTILS_LOG_WARN_NAMED(
          "rmw_fastrtps_shared_cpp",
          "Value %s unknown for environment variable RMW_FASTRTPS_PUBLICATION_MODE"
          ". Using default SYNCHRONOUS publishing mode.", env_value);
      }
    }
```

**Comment by audrow** [comment]
Thanks, @JLBuenoLopez-eProsima. I've applied your suggestions.

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
This seems reasonable I guess. @audrow will you take it out of draft mode?

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-12-16-2021/23541/1

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-january-20th-2022/23986/1

**Review by clalancette — APPROVED** [review]

**Pull request merged**
