### PR TITLE
Improve wide string (de)serialization in rwm_dynamic_fastrtps_cpp

### LINKED ISSUE #382: rmw_fastrtps_dynamic_cpp shouldn't require rosidl_typesupport_fastrtps_*
#### Feature description

Currently, it's impossible to make a single rmw single typesupport build for `rmw_fastrtps_dynamic_cpp`, as it currently depends on `rosidl_typesupport_fastrtps_c/cpp`:

https://github.com/ros2/rmw_fastrtps/blob/98d14729df0aa6d1ce01d7165d91e7cee257dd5c/rmw_fastrtps_dynamic_cpp/package.xml#L27-L28

That dependency was introduced to use some utility functions available there.
It could be removed if the utility functions are moved to a common package.

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR:

1. Moves private headers to `src`
2. Changes (de)serialization of wide strings so they don't perform `u16string` <-> `wstring` conversions
3. Fixes an off-by-one mistake in the calculation of the serialized size of wide strings
4. Removes dependencies to `rosidl_typesupport_fastrtps_c(pp)`, i.e. fixes #382

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20313/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14724/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21050/)

**Comment by MiguelCompany** [comment]
@fujitatomoya thanks for the review

I think you messed up something when launching the CI.

I would enable rmw_fastrtps_dynamic_cpp, as well as the RMWs for Cyclone and Connect, build up to test_communication and run the tests in that package to check interoperability has not been broken

**Comment by fujitatomoya** [comment]
@MiguelCompany sorry about that.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20316/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14727/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21055/)

**Comment by MiguelCompany** [comment]
@fujitatomoya @clalancette Can this be merged?

**Pull request merged**
