### PR TITLE
Complete events support

### LINKED ISSUE #356: Add support for Support for ON_REQUESTED/OFFERED_INCOMPATIBLE_QOS events
----
#### Feature description

Add support for ON_REQUESTED_INCOMPATIBLE_QOS and ON_OFFERED_INCOMPATIBLE_QOS events. This will enable `rclcpp`/`rclpy` make client callbacks regarding incompatible QoS events, which are when participants on the same topic are discovered but are unable to connect due to QoS policy incompatibilities.

This is required to complete feature request https://github.com/ros2/ros2/issues/822.

#### Implementation considerations

Extend `PubListener` and `SubListener` to respond to `on_requested_incompatible_qos` and `on_offered_incompatible_qos` callbacks respectively. Also, make the relevant changes to guard conditions for events and `takeNextEvent()`.

However, a successful implementation of this feature is blocked by https://github.com/eProsima/Fast-RTPS/issues/852.

### PR DESCRIPTION
**Pull request by MiguelCompany**
This replaces #581 and adds support for the three missing events:

* **RMW_EVENT_OFFERED_QOS_INCOMPATIBLE**: The interfaces are present and working on Fast DDS.
* **RMW_EVENT_REQUESTED_QOS_INCOMPATIBLE**: The interfaces are present and working on Fast DDS.
* **RMW_EVENT_MESSAGE_LOST**: The interfaces are present in Fast DDS, but the listener is currently never called.
  This means the RMW will behave as if messages are never lost, until we implement on_sample_lost on Fast DDS v2.6.0.

Connects to ros2/rcl#960, ros2/rclcpp#1887, and ros2/rclpy#895

Closes #356

### CODE REVIEW

**Comment by clalancette** [comment]
Here's CI for this one and https://github.com/ros2/rcl/pull/960 together:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16151/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10780/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16485/)

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by clalancette** [comment]
@MiguelCompany Unfortunately there seem to be some failing tests with this.

Besides that, I notice that when running this on my system locally I'm getting a lot of warning messages like:

```
[WARN] [1644875936.046038886] [test_negotiated_subscription]: New subscription discovered on topic '/parameter_events', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: INVALID_QOS_POLICY
```

Any thoughts on what might be going on here?

**Comment by MiguelCompany** [comment]
@clalancette 
> there seem to be some failing tests with this

I think I have fixed them with ros2/rclcpp#1887, and ros2/rclpy#895 (at least they are passing locally on my windows machine).

> when running this on my system locally I'm getting a lot of warning messages

It bothers me that it says `INVALID_QOS_POLICY`. Would you mind adding a debug message [here](https://github.com/ros2/rmw_fastrtps/pull/583/files#diff-d87580e9fb67fa5de35008b4fa2d054a34cc456ed0782aae31cbe5106df817f3R62), so we can check which policy it is complaining about?

**Comment by clalancette** [comment]
> > 
> 
> I think I have fixed them with [ros2/rclcpp#1887](https://github.com/ros2/rclcpp/pull/1887), and [ros2/rclpy#895](https://github.com/ros2/rclpy/pull/895) (at least they are passing locally on my windows machine).

Great, will run another CI with those in place.

> It bothers me that it says `INVALID_QOS_POLICY`. Would you mind adding a debug message [here](https://github.com/ros2/rmw_fastrtps/pull/583/files#diff-d87580e9fb67fa5de35008b4fa2d054a34cc456ed0782aae31cbe5106df817f3R62), so we can check which policy it is complaining about?

I'll add this and get back to you.

**Comment by clalancette** [comment]
New CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16156/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10785/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16491/)

**Comment by clalancette** [comment]
> I'll add this and get back to you.

I added a print there, and it looks like when the warning message is printed, the policy_id that is passed in is 0.  It almost looks like the `last_policy_id` that is being passed-in is always default-constructed, but that is just conjecture.

FYI you should be able to reproduce this easily by building ROS 2 from source and launch rviz2; it always shows up when it starts.  Let me know if you need any other information from me.

**Comment by fujitatomoya** [comment]
according to https://ci.ros2.org/job/ci_linux-aarch64/10785/, rclcpp and rclpy test cases have been resolved but still have the following warnings.

```
WARN] [1644942222.366270155] [my_ns.my_node]: New subscription discovered on topic 'chatter', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: INVALID
[WARN] [1644942222.367270381] [my_ns.my_node]: New publisher discovered on topic 'chatter', offering incompatible QoS. No messages will be received from it. Last incompatible policy: RELIABILITY
```

**Comment by MiguelCompany** [comment]
@clalancette I was puzzled by the message on [this failing test](https://ci.ros2.org/job/ci_linux-aarch64/10805/testReport/junit/ros2topic.ros2topic.test/test_echo_pub/test_echo_pub/) on #584.
How could it be reported that a message was lost?
And it says 0 on both `total_count` and `total_count_change`...

And I then realized the new atomic_bool fields were not being initialized.
I added commit 1248647a3069edcdb217ad56979ad62b9a4efb19 fixing that.

I hope CI gets green with it!

**Comment by clalancette** [comment]
All right, here is another try at CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16187/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10814/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16537/)

**Comment by clalancette** [comment]
CI is much closer now.  There is one failing test on Linux, and Windows still needs to finish building.  If we get that one test fixed and Windows gets happy, I think we'll be good here.

**Comment by MiguelCompany** [comment]
@clalancette we just should change the test. See [here](https://github.com/ros2/ros2cli/blob/0479d5d17ee0f7ccad2b30835d464d5aaa19bb65/ros2topic/test/test_echo_pub.py#L289)

Would you mind changing it yourself?

**Comment by clalancette** [comment]
> Would you mind changing it yourself?

Yep, done in https://github.com/ros2/ros2cli/pull/694 .  Will rerun CI with that in place.

**Comment by clalancette** [comment]
New CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16197/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10824/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16554/)

**Comment by MiguelCompany** [comment]
@clalancette I don't think the warnings on `aarch64` are related to this...

**Comment by clalancette** [comment]
> @clalancette I don't think the warnings on `aarch64` are related to this...

They definitely aren't; they are bug in the version of Eigen in Jammy.  With that, this looks really clean, so thanks for the work here!  I'm going to go ahead and merge in the whole series.

**Comment by MiguelCompany** [comment]
@clalancette Thank you very much!

Do you think this can be backported? Galactic is using the same Fast DDS version as rolling, and 2.1.1 (which is the Fast DDS version on Foxy) also has support for the incompatible QoS callbacks.

**Comment by clalancette** [comment]
> Do you think this can be backported? Galactic is using the same Fast DDS version as rolling, and 2.1.1 (which is the Fast DDS version on Foxy) also has support for the incompatible QoS callbacks.

It looks like it is ABI compatible to me, so I think we could do that.  Feel free to open up backport PRs for it, I can review.

**Pull request merged**
