### PR TITLE
[Backport Foxy] Included improvements to increase code coverage

### PR DESCRIPTION
**Pull request by ahcorde**
This PR depends on: 
  - https://github.com/ros2/rcpputils/pull/103

Included error checks, return the right code errors, avoid crashes, etc

### CODE REVIEW

**Review by brawner — APPROVED** [review]
Doing this all at once is fine with me, but can you run CI with cyclonedds only and also connextdds only to ensure it's supported by all three without issue?

**Comment by ahcorde** [comment]
@ros-pull-request-builder retest this please

**Review by hidmic — APPROVED** [review]
LGTM too.

BTW, tests are failing because of a bad assertion in `rmw_init()`, later removed in https://github.com/ros2/rmw_fastrtps/commit/b1e4aa521ac9928057c6620dbf808c682f7d06b5#diff-df05256e2b5d723055958d453bfa9bced53a2386c215b0685900ad3f761b1c8a. You'll need it.

**Comment by ahcorde** [comment]
Compiled `rmw_fastrtps_cpp rmw_fastrtps_shared_cpp rmw_fastrtps_dynamic_cpp` and tested `mw_fastrtps_cpp rmw_fastrtps_shared_cpp rmw_fastrtps_dynamic_cpp`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12708/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7669/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10422/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12654/)

**Comment by brawner** [comment]
Trying again:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12712/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7673/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10426/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12659/)

**Comment by brawner** [comment]
Also, I'm realizing it doesn't make sense to test this one on connext/cyclone. Nevermind!

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12752/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7712/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10464/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12697/)

**Pull request merged**
