### PR TITLE
Add RMW function to check QoS compatibility

### PR DESCRIPTION
**Pull request by jacobperron**
Implements https://github.com/ros2/rmw/pull/299

Depends on https://github.com/ros2/rmw_dds_common/pull/45

### CODE REVIEW

**Review by audrow — APPROVED** [review]
Looks good to me. 

Do you think it would be good to add some tests similar to in https://github.com/ros2/rmw_dds_common/pull/45 to confirm that things are hooked up correctly?

**Comment by jacobperron** [comment]
> Do you think it would be good to add some tests similar to in ros2/rmw_dds_common#45 to confirm that things are hooked up correctly?

Good call. I would say that this API is sufficiently covered by the tests further up the stack in https://github.com/ros2/rmw_implementation/pull/180, but I suppose the [quality declaration](https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md#public-api-testing-4ii) demands we exercise any new public API here as well. I'll add some tests.

**Review by mjeronimo — APPROVED** [review]

**Comment by jacobperron** [comment]
I've added some tests to exercise the new API: fe8ab7d
@audrow @mjeronimo PTAL.

**Review by audrow — APPROVED** [review]

**Comment by jacobperron** [comment]
CI: https://github.com/ros2/rmw/pull/299#issue-571521564

There's linker errors on Windows:

```
19:37:06   test_qos_profile_check_compatible.cpp

19:37:06 test_qos_profile_check_compatible.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) int __cdecl rmw_fastrtps_shared_cpp::__rmw_qos_profile_check_compatible(struct rmw_qos_profile_t,struct rmw_qos_profile_t,enum rmw_qos_compatibility_type_t *,char *,unsigned __int64)" (__imp_?__rmw_qos_profile_check_compatible@rmw_fastrtps_shared_cpp@@YAHUrmw_qos_profile_t@@0PEAW4rmw_qos_compatibility_type_t@@PEAD_K@Z) referenced in function "private: virtual void __cdecl TestQoSProfileCheckCompatible_compatible_Test::TestBody(void)" (?TestBody@TestQoSProfileCheckCompatible_compatible_Test@@EEAAXXZ) [C:\ci\ws\build\rmw_fastrtps_shared_cpp\test\test_qos_profile_check_compatible.vcxproj]

19:37:06 C:\ci\ws\build\rmw_fastrtps_shared_cpp\test\Release\test_qos_profile_check_compatible.exe : fatal error LNK1120: 1 unresolved externals [C:\ci\ws\build\rmw_fastrtps_shared_cpp\test\test_qos_profile_check_compatible.vcxproj]
```

I can reproduce locally, but I'm not sure what's wrong.. I seem to be using the visibility macro correctly. It's probably something simple that I'm overlooking.

**Comment by jacobperron** [comment]
> I can reproduce locally, but I'm not sure what's wrong.. I seem to be using the visibility macro correctly. It's probably something simple that I'm overlooking.

Apparently, we need to include the header with the function declaration (16e2e16). I don't know why though 🙃

**Comment by clalancette** [comment]
> Apparently, we need to include the header with the function declaration ([16e2e16](https://github.com/ros2/rmw_fastrtps/commit/16e2e16fb2e94ce8b76fd50187f544a6af823c0b)). I don't know why though upside_down_face

Yeah, you need to do that on Windows, otherwise the `dllexport` doesn't actually get embedded into the object file (and hence it is not actually exported).

**Comment by jacobperron** [comment]
CI: https://github.com/ros2/rmw/pull/299#issue-571521564

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
