### PR TITLE
Set more correct return values for unimplemented features (QoS)

### PR DESCRIPTION
**Pull request by emersonknapp**
To enable unit testing from Python side
Unblocks ros2/rclpy#316

Signed-off-by: Emerson Knapp <eknapp@amazon.com>

### CODE REVIEW

**Comment by sloretz** [comment]
> Requires ros2/rcl#432

`rmw_fastrtps` requires a downstream repo?

**Comment by emersonknapp** [comment]
@sloretz Nevermind I was mistaken - these two are not interdependent - but the Python one depends on both - updated comment

**Comment by sloretz** [comment]
CI (ros2/rmw_fastrtps#276 + ros2/rcl#432 testing packages up to rcl)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6946/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3205/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5702/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6773/)

**Comment by emersonknapp** [comment]
@sloretz can we merge the two?

**Comment by sloretz** [comment]
@emersonknapp Yup, Thanks for the PRs!

**Pull request merged**
