### PR TITLE
Add basic support for security logging plugin

### PR DESCRIPTION
**Pull request by kyrofa**
Support setting the security logging properties in Fast RTPS by exposing three environment variables:

- `ROS_SECURITY_LOG_FILE`: Log security events to the provided file path
- `ROS_SECURITY_LOG_PUBLISH`: Publish security events to DDS topic
- `ROS_SECURITY_LOG_VERBOSITY`: Control verbosity of logged events

This PR also makes sure this functionality is covered in tests, both with and without security enabled. Requires https://github.com/eProsima/Fast-RTPS/pull/1125 to be useful, although it doesn't break anything without it.

### CODE REVIEW

**Comment by kyrofa** [comment]
(rebased on API breakage that landed on master)

**Comment by kyrofa** [comment]
CI for rmw_fastrtps_cpp and rmw_fastrtps_shared_cpp:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10364/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5880/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8440/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10261/)

**Comment by kyrofa** [comment]
Notes for folks testing this: You'll need Fast RTPS master in order to test this, which currently only supports logging to file, so focus on testing that functionality. DDS will come soon.

**Comment by mikaelarguedas** [comment]
> That Windows msbuild warning does appear to be an related, but I have no idea why it's happening. Anyone?

It looks like you're adding a new public function to the API (apply_security_logging_configuration) that does not have visibility macros on windows.
If they are indeed public, it has to be declared as such using the macro `RMW_FASTRTPS_SHARED_CPP_PUBLIC` (that comes from rmw_fastrtps_shared_cpp/visibility_control.h). Similar to the other headers of this package:
https://github.com/ros2/rmw_fastrtps/blob/7aa97215934f6f9253d381caf52e3b54e51496e2/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp#L27
https://github.com/ros2/rmw_fastrtps/blob/7aa97215934f6f9253d381caf52e3b54e51496e2/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp#L38-L40

**Comment by kyrofa** [comment]
> If they are indeed public, it has to be declared as such using the macro 

There is no reason for callers outside of this package to need that function. In other words, there is no need for it to be public API, it's extracted for modularity and ease of testing. Does Windows actually require this?

**Comment by sloretz** [comment]
> Does Windows actually require this? Does it need to be public if it's called by a test?

Yeah @mikaelarguedas is right. It needs to be decorated with `__declspec( dllimport )` to tell the linker to look for the symbol in another dll when building the test executable. When building the library it needs the symbol to be decorated with `__declspec( dllexport )` to make that symbol available from the built dll. This is what the `*_PUBLIC` macros do. There's one for each library, and on windows it evaluates to `dllexport` when the library is building and `dllimport` for everyone else that uses the library.

**Comment by kyrofa** [comment]
Excellent, thanks for the confirmation @sloretz, fixing now.

**Comment by kyrofa** [comment]
Alright trying again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10379/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5894/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8462/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10276/)

**Comment by kyrofa** [comment]
Hey, there's the green! Thanks again guys.

**Comment by kyrofa** [comment]
Is this good to merge, or are we waiting for more?

**Comment by sloretz** [comment]
> Is this good to merge, or are we waiting for more?

If I understand correctly I think this one is waiting on eProsima/Fast-RTPS#1125 to be ready on the [Fast-RTPS `1.10.x` branch](https://github.com/ros2/ros2/blob/0a62b2cd2210b06be7570c00922cd2f3d6609e31/ros2.repos#L34-L37). I'm having a look at the `rmw_conntext` PR now.

**Comment by kyrofa** [comment]
Thanks @sloretz. In case it matters, note that the properties set by this PR are only used from https://github.com/eProsima/Fast-RTPS/pull/1125 onward, but setting them shouldn't cause issues without it. They're just ignored based on my tests.

**Comment by sloretz** [comment]
CI again now that ros2/ros2#906 has been merged (Testing just rmw_fastrtps_cpp rmw_fastrtps_shared_cpp)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10539/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5995/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8585/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10411/)

**Comment by sloretz** [comment]
@kyrofa Mind rebasing? I suspect the build failure is just this branch missing #373

```
14:48:03 /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_request.cpp:36:1: error: conflicting declaration of C function ‘rmw_ret_t rmw_take_request(const rmw_service_t*, rmw_request_id_t*, void*, bool*)’
14:48:03    36 | rmw_take_request(
14:48:03       | ^~~~~~~~~~~~~~~~
14:48:03 In file included from /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_request.cpp:16:
14:48:03 /home/jenkins-agent/workspace/ci_linux/ws/install/rmw/include/rmw/rmw.h:979:1: note: previous declaration ‘rmw_ret_t rmw_take_request(const rmw_service_t*, rmw_service_info_t*, void*, bool*)’
14:48:03   979 | rmw_take_request(
14:48:03       | ^~~~~~~~~~~~~~~~
14:48:03 make[2]: *** [CMakeFiles/rmw_fastrtps_cpp.dir/build.make:375: CMakeFiles/rmw_fastrtps_cpp.dir/src/rmw_request.cpp.o] Error 1
14:48:03 make[2]: *** Waiting for unfinished jobs....
14:48:03 /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_publisher.cpp:38:9: error: ‘rosidl_message_bounds_t’ does not name a type
14:48:03    38 |   const rosidl_message_bounds_t * message_bounds,
14:48:03       |         ^~~~~~~~~~~~~~~~~~~~~~~
14:48:03 /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_publisher.cpp:36:1: error: conflicting declaration of C function ‘rmw_ret_t rmw_init_publisher_allocation(const rosidl_message_type_support_t*, const int*, rmw_publisher_allocation_t*)’
14:48:03    36 | rmw_init_publisher_allocation(
14:48:03       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:48:03 In file included from /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_publisher.cpp:20:
14:48:03 /home/jenkins-agent/workspace/ci_linux/ws/install/rmw/include/rmw/rmw.h:277:1: note: previous declaration ‘rmw_ret_t rmw_init_publisher_allocation(const rosidl_message_type_support_t*, const rosidl_runtime_c__Sequence__bound*, rmw_publisher_allocation_t*)’
14:48:03   277 | rmw_init_publisher_allocation(
14:48:03       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:48:03 make[2]: *** [CMakeFiles/rmw_fastrtps_cpp.dir/build.make:362: CMakeFiles/rmw_fastrtps_cpp.dir/src/rmw_publisher.cpp.o] Error 1
14:48:03 make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/rmw_fastrtps_cpp.dir/all] Error 2
```

**Comment by kyrofa** [comment]
@sloretz done, tests appear to pass locally.

**Comment by kyrofa** [comment]
Running the tests in the build farm again (for rmw_fastrtps_cpp rmw_fastrtps_shared_cpp):

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10561/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6014/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8601/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10443/)

**Comment by kyrofa** [comment]
@sloretz tests are green there now, although I'm not sure what's going on with Fpr__rmw_fastrtps__ubuntu_focal_amd64.

**Comment by sloretz** [comment]
> I'm not sure what's going on with Fpr__rmw_fastrtps__ubuntu_focal_amd64.

Looks unrelated to this PR. Packages required by this repo have not been built yet. First [rmw_dds_common](http://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__rmw_dds_common__ubuntu_focal_amd64__binary/) has not been built because  [rosidl_default_generators](http://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__rosidl_default_generators__ubuntu_focal_amd64__binary/) and [rosidl_default_runtime](http://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__rosidl_default_runtime__ubuntu_focal_amd64__binary/) have not been built because [rosidl_generator_py](http://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__rosidl_generator_py__ubuntu_focal_amd64__binary/7/) failed to build.

**Comment by sloretz** [comment]
@jacobperron I think this one is good to merge. It doesn't change API and was ready before the API freeze, but was on hold for ros2/ros2#906. Ok to merge?

**Comment by jacobperron** [comment]
@sloretz I think it's okay to merge (you can disregard the PR job failure; working on it).

**Pull request merged**
