### PR TITLE
Add missing lock guards for discovered_names and discovered_namespaces

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/rmw_fastrtps/issues/299.

### CODE REVIEW

**Comment by ivanpauno** [comment]
Checking if this avoids the warning (using same build options as nightly_linux_clang_libcxx):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7484/)

**Comment by ivanpauno** [comment]
@MiguelCompany Could you check if this is fine?

**Comment by ivanpauno** [comment]
CI (with usual build option, only fastrtps):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7485/)

**Comment by MiguelCompany** [comment]
> @MiguelCompany Could you check if this is fine?

Seems fine to me. The test `test_find_container_node_names` seems to have been failing intermittently since June 13th

**Comment by ivanpauno** [comment]
> > @MiguelCompany Could you check if this is fine?
> 
> Seems fine to me. The test `test_find_container_node_names` seems to have been failing intermittently since June 13th

Sorry, but I haven't found that test failing on `nightly_linux_repeated` job. Could you copy a link?
Thanks!

**Comment by MiguelCompany** [comment]
I found it on [nightly_linux_release](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1202/testReport/junit/ros2component.test/test_api/test_find_container_node_names/) and [nightly_win_rel](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1217/testReport/junit/ros2component.test/test_api/test_find_container_node_names/)

**Comment by ivanpauno** [comment]
> I found it on [nightly_linux_release](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1202/testReport/junit/ros2component.test/test_api/test_find_container_node_names/) and [nightly_win_rel](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1217/testReport/junit/ros2component.test/test_api/test_find_container_node_names/)

Thanks! I asked again because it could be related, but it was just bad look.
Here CI passing with this change:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7508/)

**Pull request merged**
