### PR TITLE
[foxy] Discriminate when the Client has gone from when the Client has not completely matched

### PR DESCRIPTION
**Pull request by jacobperron**
Attempt to backport #467 to Foxy in an ABI compatible way.

I *think* this is an ABI compatible port; I'll let the ABI checking tell me otherwise.

### CODE REVIEW

**Comment by jacobperron** [comment]
The ABI checker is failing for some reason other than the changes in this PR. The same failure occurred when performing an innocent update the package.xml in https://github.com/ros2/rmw_fastrtps/pull/474. I've opened a separate PR that I think addresses the compilation error during the ABI check: https://github.com/ros2/rmw_fastrtps/pull/480

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please

**Review by hidmic — APPROVED** [review]
LGTM pending green CI

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13068/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8014/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10791/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13048/)

**Comment by bednarhonza** [comment]
Hello,
I still have the same issue as mentioned in this thread. I posted the error just to make sure. It has happened repetadly during the last weeks.

`[component_container_mt-1]   what():  failed to send response: client will not receive response, at /tmp/binarydeb/ros-foxy-rmw-fastrtps-shared-cpp-1.2.6/src/rmw_response.cpp:126, at /tmp/binarydeb/ros-foxy-rcl-1.1.11/src/rcl/service.c:356`

I have Ubuntu 20.04 and up-to-date Foxy packages.

Thanks!

**Comment by AnushaPulichintha** [comment]
Hello, I also have the same issue on  Ubuntu 20.04 and foxy binary. 
` what():  failed to send response: client will not receive response, at /tmp/binarydeb/ros-foxy-rmw-fastrtps-shared-cpp-1.2.6/src/rmw_response.cpp:126, at /tmp/binarydeb/ros-foxy-rcl-1.1.11/src/rcl/service.c:356`

can it be tested again?

Thanks!!

**Pull request merged**
