### PR TITLE
[Foxy] Remove unnecessary includes

### PR DESCRIPTION
**Pull request by MiguelCompany**
Backport #487 into foxy.

Should fix the build issues on windows for ros2/ros2#1114 and ros2/ros2#1113

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM, thanks!

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14364/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9143/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12043/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14462/)

**Comment by jacobperron** [comment]
Interestingly, this change result in a compiler error:
```
09:04:24 /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_node.cpp:39:1: error: conflicting declaration of C function ‘rmw_node_t* rmw_create_node(rmw_context_t*, const char*, const char*, size_t, bool)’
09:04:24    39 | rmw_create_node(
09:04:24       | ^~~~~~~~~~~~~~~
09:04:24 In file included from /home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/rmw_node.cpp:27:
09:04:24 /home/jenkins-agent/workspace/ci_linux/ws/install/rmw/include/rmw/rmw.h:167:1: note: previous declaration ‘rmw_node_t* rmw_create_node(rmw_context_t*, const char*, const char*)’
09:04:24   167 | rmw_create_node(
09:04:24       | ^~~~~~~~~~~~~~~
09:04:24 make[2]: *** [CMakeFiles/rmw_fastrtps_cpp.dir/build.make:310: CMakeFiles/rmw_fastrtps_cpp.dir/src/rmw_node.cpp.o] Error 1
09:04:24 make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/rmw_fastrtps_cpp.dir/all] Error 2
```

I'm not sure why.. @MiguelCompany, any ideas?

**Comment by MiguelCompany** [comment]
@jacobperron Looking at the repos file used on the build seems it was using the master repos instead of the foxy ones.

**Comment by jacobperron** [comment]
> @jacobperron Looking at the repos file used on the build seems it was using the master repos instead of the foxy ones.

:upside_down_face: You are totally correct; my mistake. Let's try this again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14423/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9195/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12096/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14523/)

**Comment by jacobperron** [comment]
I haven't had a chance to look in detail yet, but I triggered a Windows build for the current state of Foxy for comparison: https://ci.ros2.org/job/ci_windows/14536/

It looks like there are some discrepancies.

**Comment by hidmic** [comment]
@MiguelCompany friendly ping, I get we need this to Fast-DDS 2.1.x out for Foxy.

**Comment by MiguelCompany** [comment]
@hidmic I will try to check locally tomorrow, but I don't see how the failures could be related. Would you mind launching CI again just in case?

**Comment by MiguelCompany** [comment]
@hidmic I have checked locally on Windows, and I have the same test results with this PR and without it.

After importing [this repos](https://github.com/ros2/ros2/blob/fce5bc4192c805bac333b353a2daa87458d7518c/ros2.repos) I had the same failures as on the CI run. The result of `vcs export --exact-with-tags src` was:

<details>
<pre>
repositories:
  ament\ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: 589cf00e21b100f2844b127bb53743b7bf29ee7b
  ament\ament_index:
    type: git
    url: https://github.com/ament/ament_index.git
    version: ff71598b04732d9a8378e1f258f4e3803faf598c
  ament\ament_lint:
    type: git
    url: https://github.com/ament/ament_lint.git
    version: 0.9.6
  ament\ament_package:
    type: git
    url: https://github.com/ament/ament_package.git
    version: 0.9.5
  ament\google_benchmark_vendor:
    type: git
    url: https://github.com/ament/google_benchmark_vendor.git
    version: 9416ce954dd66778b1d92c9bb57248fa4c39fa12
  ament\googletest:
    type: git
    url: https://github.com/ament/googletest.git
    version: 69ff0aa660dd25ecdc8a1fe91505c3c58e0032c2
  ament\uncrustify_vendor:
    type: git
    url: https://github.com/ament/uncrustify_vendor.git
    version: 1.4.0
  eProsima\Fast-CDR:
    type: git
    url: https://github.com/eProsima/Fast-CDR.git
    version: v1.0.13
  eProsima\Fast-DDS:
    type: git
    url: https://github.com/eProsima/Fast-DDS.git
    version: 6761902870808319126a7372659d952a665dadd4
  eProsima\foonathan_memory_vendor:
    type: git
    url: https://github.com/eProsima/foonathan_memory_vendor.git
    version: 0be8f746ee33b3366528d2533087754ce14732b0
  eclipse-cyclonedds\cyclonedds:
    type: git
    url: https://github.com/eclipse-cyclonedds/cyclonedds.git
    version: 457a07132d394e6461ca23a5c27ddaefbb8ab868
  osrf\osrf_pycommon:
    type: git
    url: https://github.com/osrf/osrf_pycommon.git
    version: 0.1.10
  osrf\osrf_testing_tools_cpp:
    type: git
    url: https://github.com/osrf/osrf_testing_tools_cpp.git
    version: 888cc036c068690ddb5123daf729cbb3e86844f4
  ros-perception\laser_geometry:
    type: git
    url: https://github.com/ros-perception/laser_geometry.git
    version: 2.2.0
  ros-planning\navigation_msgs:
    type: git
    url: https://github.com/ros-planning/navigation_msgs.git
    version: 2.0.2
  ros-tooling\libstatistics_collector:
    type: git
    url: https://github.com/ros-tooling/libstatistics_collector.git
    version: 562e0dd9e388ef4309b4630f2fc731d949235465
  ros-tracing\ros2_tracing:
    type: git
    url: https://gitlab.com/ros-tracing/ros2_tracing.git
    version: 6535577457eb8fb8ec23373b0829590b27ff50c0
  ros-visualization\interactive_markers:
    type: git
    url: https://github.com/ros-visualization/interactive_markers.git
    version: 2.1.3
  ros-visualization\python_qt_binding:
    type: git
    url: https://github.com/ros-visualization/python_qt_binding.git
    version: 0af15bad975f1829e36b2eaa3ee23457aa2b2588
  ros-visualization\qt_gui_core:
    type: git
    url: https://github.com/ros-visualization/qt_gui_core.git
    version: 582357fa18023b2a726e99160b73a24278e78f64
  ros-visualization\rqt:
    type: git
    url: https://github.com/ros-visualization/rqt.git
    version: 943797aed6f86cbc0ec8619592ff2f17337e605d
  ros-visualization\rqt_action:
    type: git
    url: https://github.com/ros-visualization/rqt_action.git
    version: 0f24c9dd29825ea0e9de2bfdd15ac81b75e54004
  ros-visualization\rqt_console:
    type: git
    url: https://github.com/ros-visualization/rqt_console.git
    version: 107fb7007e8defdaac29d065581875180d925638
  ros-visualization\rqt_graph:
    type: git
    url: https://github.com/ros-visualization/rqt_graph.git
    version: 1.1.2
  ros-visualization\rqt_msg:
    type: git
    url: https://github.com/ros-visualization/rqt_msg.git
    version: 1.0.4
  ros-visualization\rqt_plot:
    type: git
    url: https://github.com/ros-visualization/rqt_plot.git
    version: 58d628a57e1c90f010f0f28d0218863f6537c72e
  ros-visualization\rqt_publisher:
    type: git
    url: https://github.com/ros-visualization/rqt_publisher.git
    version: 1.1.2
  ros-visualization\rqt_py_console:
    type: git
    url: https://github.com/ros-visualization/rqt_py_console.git
    version: 1.0.1
  ros-visualization\rqt_reconfigure:
    type: git
    url: https://github.com/ros-visualization/rqt_reconfigure.git
    version: 1.0.8
  ros-visualization\rqt_service_caller:
    type: git
    url: https://github.com/ros-visualization/rqt_service_caller.git
    version: 1.0.4
  ros-visualization\rqt_shell:
    type: git
    url: https://github.com/ros-visualization/rqt_shell.git
    version: 1.0.1
  ros-visualization\rqt_srv:
    type: git
    url: https://github.com/ros-visualization/rqt_srv.git
    version: 1.0.2
  ros-visualization\rqt_top:
    type: git
    url: https://github.com/ros-visualization/rqt_top.git
    version: 1.0.1
  ros-visualization\rqt_topic:
    type: git
    url: https://github.com/ros-visualization/rqt_topic.git
    version: 22d70f6c2b33d4a1d09ef7cff0234da59657e5db
  ros-visualization\tango_icons_vendor:
    type: git
    url: https://github.com/ros-visualization/tango_icons_vendor.git
    version: 0.1.0
  ros2\ament_cmake_ros:
    type: git
    url: https://github.com/ros2/ament_cmake_ros.git
    version: 0.9.2
  ros2\common_interfaces:
    type: git
    url: https://github.com/ros2/common_interfaces.git
    version: 2.0.4
  ros2\console_bridge_vendor:
    type: git
    url: https://github.com/ros2/console_bridge_vendor.git
    version: 1.2.4
  ros2\demos:
    type: git
    url: https://github.com/ros2/demos.git
    version: b0c1389ae61172788cccf4eb4e34b3b84c408a9d
  ros2\eigen3_cmake_module:
    type: git
    url: https://github.com/ros2/eigen3_cmake_module.git
    version: 0.1.1
  ros2\example_interfaces:
    type: git
    url: https://github.com/ros2/example_interfaces.git
    version: 0.9.1
  ros2\examples:
    type: git
    url: https://github.com/ros2/examples.git
    version: 0.9.4
  ros2\geometry2:
    type: git
    url: https://github.com/ros2/geometry2.git
    version: 5f30fe8fcc9eacde580fb1374ae82182e7fb5bb6
  ros2\launch:
    type: git
    url: https://github.com/ros2/launch.git
    version: 0.10.5
  ros2\launch_ros:
    type: git
    url: https://github.com/ros2/launch_ros.git
    version: 874412408e1077b9b38de5ee3ff8a0de6481c05f
  ros2\libyaml_vendor:
    type: git
    url: https://github.com/ros2/libyaml_vendor.git
    version: 1.0.4
  ros2\message_filters:
    type: git
    url: https://github.com/ros2/message_filters.git
    version: 3.2.5
  ros2\mimick_vendor:
    type: git
    url: https://github.com/ros2/mimick_vendor.git
    version: 8c738197e8d3511dd4344eb871e5c48392b7c673
  ros2\orocos_kinematics_dynamics:
    type: git
    url: https://github.com/ros2/orocos_kinematics_dynamics.git
    version: 3.3.2
  ros2\performance_test_fixture:
    type: git
    url: https://github.com/ros2/performance_test_fixture.git
    version: 0.0.7
  ros2\python_cmake_module:
    type: git
    url: https://github.com/ros2/python_cmake_module.git
    version: 0.8.1
  ros2\rcl:
    type: git
    url: https://github.com/ros2/rcl.git
    version: 1.1.11
  ros2\rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: ee04e046132be9d9fdcdaeff8dd54a5d0d9aa022
  ros2\rcl_logging:
    type: git
    url: https://github.com/ros2/rcl_logging.git
    version: 1.1.0
  ros2\rclcpp:
    type: git
    url: https://github.com/ros2/rclcpp.git
    version: 1c92622516d676a7a5f8075b241410d8d498dd9f
  ros2\rclpy:
    type: git
    url: https://github.com/ros2/rclpy.git
    version: 87a88a939691bd48aea6b963e083d0a97380933f
  ros2\rcpputils:
    type: git
    url: https://github.com/ros2/rcpputils.git
    version: 13b04da7864c3f0afe8a6834ad84c22ca389a4f8
  ros2\rcutils:
    type: git
    url: https://github.com/ros2/rcutils.git
    version: 1.1.3
  ros2\realtime_support:
    type: git
    url: https://github.com/ros2/realtime_support.git
    version: 0.9.0
  ros2\rmw:
    type: git
    url: https://github.com/ros2/rmw.git
    version: 1.0.3
  ros2\rmw_connext:
    type: git
    url: https://github.com/ros2/rmw_connext.git
    version: 1.0.3
  ros2\rmw_cyclonedds:
    type: git
    url: https://github.com/ros2/rmw_cyclonedds.git
    version: 0.7.6
  ros2\rmw_dds_common:
    type: git
    url: https://github.com/ros2/rmw_dds_common.git
    version: 1.0.3
  ros2\rmw_fastrtps:
    type: git
    url: https://github.com/ros2/rmw_fastrtps.git
    version: 1.2.5
  ros2\rmw_implementation:
    type: git
    url: https://github.com/ros2/rmw_implementation.git
    version: 1.0.2
  ros2\ros1_bridge:
    type: git
    url: https://github.com/ros2/ros1_bridge.git
    version: 0.9.6
  ros2\ros2cli:
    type: git
    url: https://github.com/ros2/ros2cli.git
    version: 0.9.9
  ros2\ros2cli_common_extensions:
    type: git
    url: https://github.com/ros2/ros2cli_common_extensions.git
    version: 0.1.1
  ros2\ros_testing:
    type: git
    url: https://github.com/ros2/ros_testing.git
    version: 0.2.1
  ros2\rosbag2:
    type: git
    url: https://github.com/ros2/rosbag2.git
    version: 0.3.7
  ros2\rosidl:
    type: git
    url: https://github.com/ros2/rosidl.git
    version: 1.2.1
  ros2\rosidl_dds:
    type: git
    url: https://github.com/ros2/rosidl_dds.git
    version: 0.7.1
  ros2\rosidl_defaults:
    type: git
    url: https://github.com/ros2/rosidl_defaults.git
    version: 1.0.1
  ros2\rosidl_python:
    type: git
    url: https://github.com/ros2/rosidl_python.git
    version: 0.9.4
  ros2\rosidl_runtime_py:
    type: git
    url: https://github.com/ros2/rosidl_runtime_py.git
    version: 0.9.1
  ros2\rosidl_typesupport:
    type: git
    url: https://github.com/ros2/rosidl_typesupport.git
    version: 1.0.2
  ros2\rosidl_typesupport_connext:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_connext.git
    version: 1.0.3
  ros2\rosidl_typesupport_fastrtps:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_fastrtps.git
    version: 1.0.3
  ros2\rpyutils:
    type: git
    url: https://github.com/ros2/rpyutils.git
    version: 0.2.0
  ros2\rviz:
    type: git
    url: https://github.com/ros2/rviz.git
    version: e19a0750c4495646183ed819de62c7fea7a2624d
  ros2\spdlog_vendor:
    type: git
    url: https://github.com/ros2/spdlog_vendor.git
    version: 1.1.3
  ros2\sros2:
    type: git
    url: https://github.com/ros2/sros2.git
    version: 0.9.4
  ros2\system_tests:
    type: git
    url: https://github.com/ros2/system_tests.git
    version: 0.9.1
  ros2\test_interface_files:
    type: git
    url: https://github.com/ros2/test_interface_files.git
    version: 0.8.1
  ros2\tinyxml2_vendor:
    type: git
    url: https://github.com/ros2/tinyxml2_vendor.git
    version: 0.7.4
  ros2\tinyxml_vendor:
    type: git
    url: https://github.com/ros2/tinyxml_vendor.git
    version: 0.8.2
  ros2\tlsf:
    type: git
    url: https://github.com/ros2/tlsf.git
    version: 0.5.0
  ros2\unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: 2.1.3
  ros2\urdf:
    type: git
    url: https://github.com/ros2/urdf.git
    version: 2.4.0
  ros2\yaml_cpp_vendor:
    type: git
    url: https://github.com/ros2/yaml_cpp_vendor.git
    version: 7.0.2
  ros\class_loader:
    type: git
    url: https://github.com/ros/class_loader.git
    version: 2.0.2
  ros\kdl_parser:
    type: git
    url: https://github.com/ros/kdl_parser.git
    version: 2.4.1
  ros\pluginlib:
    type: git
    url: https://github.com/ros/pluginlib.git
    version: 0eb530890717c53a29d670b9fd07badbad22b57a
  ros\resource_retriever:
    type: git
    url: https://github.com/ros/resource_retriever.git
    version: 2.3.4
  ros\robot_state_publisher:
    type: git
    url: https://github.com/ros/robot_state_publisher.git
    version: 2.4.2
  ros\ros_environment:
    type: git
    url: https://github.com/ros/ros_environment.git
    version: 2.5.0
  ros\ros_tutorials:
    type: git
    url: https://github.com/ros/ros_tutorials.git
    version: 1fd5ea7c166837ce01a0fb4d00133987ed08d78d
  ros\urdfdom:
    type: git
    url: https://github.com/ros/urdfdom.git
    version: 2.3.3
  ros\urdfdom_headers:
    type: git
    url: https://github.com/ros/urdfdom_headers.git
    version: 8ec38993c21c6913602b9519ca07e4e018af88b5
</pre>
</details>

I then did a checkout of the source branch of this PR, removed `build` and `install` folders, run the tests again, and the results were the same. The result of `vcs export --exact-with-tags src` was:

<details>
<pre>
repositories:
  ament\ament_cmake:
    type: git
    url: https://github.com/ament/ament_cmake.git
    version: 589cf00e21b100f2844b127bb53743b7bf29ee7b
  ament\ament_index:
    type: git
    url: https://github.com/ament/ament_index.git
    version: ff71598b04732d9a8378e1f258f4e3803faf598c
  ament\ament_lint:
    type: git
    url: https://github.com/ament/ament_lint.git
    version: 0.9.6
  ament\ament_package:
    type: git
    url: https://github.com/ament/ament_package.git
    version: 0.9.5
  ament\google_benchmark_vendor:
    type: git
    url: https://github.com/ament/google_benchmark_vendor.git
    version: 9416ce954dd66778b1d92c9bb57248fa4c39fa12
  ament\googletest:
    type: git
    url: https://github.com/ament/googletest.git
    version: 69ff0aa660dd25ecdc8a1fe91505c3c58e0032c2
  ament\uncrustify_vendor:
    type: git
    url: https://github.com/ament/uncrustify_vendor.git
    version: 1.4.0
  eProsima\Fast-CDR:
    type: git
    url: https://github.com/eProsima/Fast-CDR.git
    version: v1.0.13
  eProsima\Fast-DDS:
    type: git
    url: https://github.com/eProsima/Fast-DDS.git
    version: 6761902870808319126a7372659d952a665dadd4
  eProsima\foonathan_memory_vendor:
    type: git
    url: https://github.com/eProsima/foonathan_memory_vendor.git
    version: 0be8f746ee33b3366528d2533087754ce14732b0
  eclipse-cyclonedds\cyclonedds:
    type: git
    url: https://github.com/eclipse-cyclonedds/cyclonedds.git
    version: 457a07132d394e6461ca23a5c27ddaefbb8ab868
  osrf\osrf_pycommon:
    type: git
    url: https://github.com/osrf/osrf_pycommon.git
    version: 0.1.10
  osrf\osrf_testing_tools_cpp:
    type: git
    url: https://github.com/osrf/osrf_testing_tools_cpp.git
    version: 888cc036c068690ddb5123daf729cbb3e86844f4
  ros-perception\laser_geometry:
    type: git
    url: https://github.com/ros-perception/laser_geometry.git
    version: 2.2.0
  ros-planning\navigation_msgs:
    type: git
    url: https://github.com/ros-planning/navigation_msgs.git
    version: 2.0.2
  ros-tooling\libstatistics_collector:
    type: git
    url: https://github.com/ros-tooling/libstatistics_collector.git
    version: 562e0dd9e388ef4309b4630f2fc731d949235465
  ros-tracing\ros2_tracing:
    type: git
    url: https://gitlab.com/ros-tracing/ros2_tracing.git
    version: 6535577457eb8fb8ec23373b0829590b27ff50c0
  ros-visualization\interactive_markers:
    type: git
    url: https://github.com/ros-visualization/interactive_markers.git
    version: 2.1.3
  ros-visualization\python_qt_binding:
    type: git
    url: https://github.com/ros-visualization/python_qt_binding.git
    version: 0af15bad975f1829e36b2eaa3ee23457aa2b2588
  ros-visualization\qt_gui_core:
    type: git
    url: https://github.com/ros-visualization/qt_gui_core.git
    version: 582357fa18023b2a726e99160b73a24278e78f64
  ros-visualization\rqt:
    type: git
    url: https://github.com/ros-visualization/rqt.git
    version: 943797aed6f86cbc0ec8619592ff2f17337e605d
  ros-visualization\rqt_action:
    type: git
    url: https://github.com/ros-visualization/rqt_action.git
    version: 0f24c9dd29825ea0e9de2bfdd15ac81b75e54004
  ros-visualization\rqt_console:
    type: git
    url: https://github.com/ros-visualization/rqt_console.git
    version: 107fb7007e8defdaac29d065581875180d925638
  ros-visualization\rqt_graph:
    type: git
    url: https://github.com/ros-visualization/rqt_graph.git
    version: 1.1.2
  ros-visualization\rqt_msg:
    type: git
    url: https://github.com/ros-visualization/rqt_msg.git
    version: 1.0.4
  ros-visualization\rqt_plot:
    type: git
    url: https://github.com/ros-visualization/rqt_plot.git
    version: 58d628a57e1c90f010f0f28d0218863f6537c72e
  ros-visualization\rqt_publisher:
    type: git
    url: https://github.com/ros-visualization/rqt_publisher.git
    version: 1.1.2
  ros-visualization\rqt_py_console:
    type: git
    url: https://github.com/ros-visualization/rqt_py_console.git
    version: 1.0.1
  ros-visualization\rqt_reconfigure:
    type: git
    url: https://github.com/ros-visualization/rqt_reconfigure.git
    version: 1.0.8
  ros-visualization\rqt_service_caller:
    type: git
    url: https://github.com/ros-visualization/rqt_service_caller.git
    version: 1.0.4
  ros-visualization\rqt_shell:
    type: git
    url: https://github.com/ros-visualization/rqt_shell.git
    version: 1.0.1
  ros-visualization\rqt_srv:
    type: git
    url: https://github.com/ros-visualization/rqt_srv.git
    version: 1.0.2
  ros-visualization\rqt_top:
    type: git
    url: https://github.com/ros-visualization/rqt_top.git
    version: 1.0.1
  ros-visualization\rqt_topic:
    type: git
    url: https://github.com/ros-visualization/rqt_topic.git
    version: 22d70f6c2b33d4a1d09ef7cff0234da59657e5db
  ros-visualization\tango_icons_vendor:
    type: git
    url: https://github.com/ros-visualization/tango_icons_vendor.git
    version: 0.1.0
  ros2\ament_cmake_ros:
    type: git
    url: https://github.com/ros2/ament_cmake_ros.git
    version: 0.9.2
  ros2\common_interfaces:
    type: git
    url: https://github.com/ros2/common_interfaces.git
    version: 2.0.4
  ros2\console_bridge_vendor:
    type: git
    url: https://github.com/ros2/console_bridge_vendor.git
    version: 1.2.4
  ros2\demos:
    type: git
    url: https://github.com/ros2/demos.git
    version: b0c1389ae61172788cccf4eb4e34b3b84c408a9d
  ros2\eigen3_cmake_module:
    type: git
    url: https://github.com/ros2/eigen3_cmake_module.git
    version: 0.1.1
  ros2\example_interfaces:
    type: git
    url: https://github.com/ros2/example_interfaces.git
    version: 0.9.1
  ros2\examples:
    type: git
    url: https://github.com/ros2/examples.git
    version: 0.9.4
  ros2\geometry2:
    type: git
    url: https://github.com/ros2/geometry2.git
    version: 5f30fe8fcc9eacde580fb1374ae82182e7fb5bb6
  ros2\launch:
    type: git
    url: https://github.com/ros2/launch.git
    version: 0.10.5
  ros2\launch_ros:
    type: git
    url: https://github.com/ros2/launch_ros.git
    version: 874412408e1077b9b38de5ee3ff8a0de6481c05f
  ros2\libyaml_vendor:
    type: git
    url: https://github.com/ros2/libyaml_vendor.git
    version: 1.0.4
  ros2\message_filters:
    type: git
    url: https://github.com/ros2/message_filters.git
    version: 3.2.5
  ros2\mimick_vendor:
    type: git
    url: https://github.com/ros2/mimick_vendor.git
    version: 8c738197e8d3511dd4344eb871e5c48392b7c673
  ros2\orocos_kinematics_dynamics:
    type: git
    url: https://github.com/ros2/orocos_kinematics_dynamics.git
    version: 3.3.2
  ros2\performance_test_fixture:
    type: git
    url: https://github.com/ros2/performance_test_fixture.git
    version: 0.0.7
  ros2\python_cmake_module:
    type: git
    url: https://github.com/ros2/python_cmake_module.git
    version: 0.8.1
  ros2\rcl:
    type: git
    url: https://github.com/ros2/rcl.git
    version: 1.1.11
  ros2\rcl_interfaces:
    type: git
    url: https://github.com/ros2/rcl_interfaces.git
    version: ee04e046132be9d9fdcdaeff8dd54a5d0d9aa022
  ros2\rcl_logging:
    type: git
    url: https://github.com/ros2/rcl_logging.git
    version: 1.1.0
  ros2\rclcpp:
    type: git
    url: https://github.com/ros2/rclcpp.git
    version: 1c92622516d676a7a5f8075b241410d8d498dd9f
  ros2\rclpy:
    type: git
    url: https://github.com/ros2/rclpy.git
    version: 87a88a939691bd48aea6b963e083d0a97380933f
  ros2\rcpputils:
    type: git
    url: https://github.com/ros2/rcpputils.git
    version: 13b04da7864c3f0afe8a6834ad84c22ca389a4f8
  ros2\rcutils:
    type: git
    url: https://github.com/ros2/rcutils.git
    version: 1.1.3
  ros2\realtime_support:
    type: git
    url: https://github.com/ros2/realtime_support.git
    version: 0.9.0
  ros2\rmw:
    type: git
    url: https://github.com/ros2/rmw.git
    version: 1.0.3
  ros2\rmw_connext:
    type: git
    url: https://github.com/ros2/rmw_connext.git
    version: 1.0.3
  ros2\rmw_cyclonedds:
    type: git
    url: https://github.com/ros2/rmw_cyclonedds.git
    version: 0.7.6
  ros2\rmw_dds_common:
    type: git
    url: https://github.com/ros2/rmw_dds_common.git
    version: 1.0.3
  ros2\rmw_fastrtps:
    type: git
    url: https://github.com/eProsima/rmw_fastrtps.git
    version: 188501fb613cfc0d80a5bbc27f0c43dfd5e7dcd3
  ros2\rmw_implementation:
    type: git
    url: https://github.com/ros2/rmw_implementation.git
    version: 1.0.2
  ros2\ros1_bridge:
    type: git
    url: https://github.com/ros2/ros1_bridge.git
    version: 0.9.6
  ros2\ros2cli:
    type: git
    url: https://github.com/ros2/ros2cli.git
    version: 0.9.9
  ros2\ros2cli_common_extensions:
    type: git
    url: https://github.com/ros2/ros2cli_common_extensions.git
    version: 0.1.1
  ros2\ros_testing:
    type: git
    url: https://github.com/ros2/ros_testing.git
    version: 0.2.1
  ros2\rosbag2:
    type: git
    url: https://github.com/ros2/rosbag2.git
    version: 0.3.7
  ros2\rosidl:
    type: git
    url: https://github.com/ros2/rosidl.git
    version: 1.2.1
  ros2\rosidl_dds:
    type: git
    url: https://github.com/ros2/rosidl_dds.git
    version: 0.7.1
  ros2\rosidl_defaults:
    type: git
    url: https://github.com/ros2/rosidl_defaults.git
    version: 1.0.1
  ros2\rosidl_python:
    type: git
    url: https://github.com/ros2/rosidl_python.git
    version: 0.9.4
  ros2\rosidl_runtime_py:
    type: git
    url: https://github.com/ros2/rosidl_runtime_py.git
    version: 0.9.1
  ros2\rosidl_typesupport:
    type: git
    url: https://github.com/ros2/rosidl_typesupport.git
    version: 1.0.2
  ros2\rosidl_typesupport_connext:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_connext.git
    version: 1.0.3
  ros2\rosidl_typesupport_fastrtps:
    type: git
    url: https://github.com/ros2/rosidl_typesupport_fastrtps.git
    version: 1.0.3
  ros2\rpyutils:
    type: git
    url: https://github.com/ros2/rpyutils.git
    version: 0.2.0
  ros2\rviz:
    type: git
    url: https://github.com/ros2/rviz.git
    version: e19a0750c4495646183ed819de62c7fea7a2624d
  ros2\spdlog_vendor:
    type: git
    url: https://github.com/ros2/spdlog_vendor.git
    version: 1.1.3
  ros2\sros2:
    type: git
    url: https://github.com/ros2/sros2.git
    version: 0.9.4
  ros2\system_tests:
    type: git
    url: https://github.com/ros2/system_tests.git
    version: 0.9.1
  ros2\test_interface_files:
    type: git
    url: https://github.com/ros2/test_interface_files.git
    version: 0.8.1
  ros2\tinyxml2_vendor:
    type: git
    url: https://github.com/ros2/tinyxml2_vendor.git
    version: 0.7.4
  ros2\tinyxml_vendor:
    type: git
    url: https://github.com/ros2/tinyxml_vendor.git
    version: 0.8.2
  ros2\tlsf:
    type: git
    url: https://github.com/ros2/tlsf.git
    version: 0.5.0
  ros2\unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: 2.1.3
  ros2\urdf:
    type: git
    url: https://github.com/ros2/urdf.git
    version: 2.4.0
  ros2\yaml_cpp_vendor:
    type: git
    url: https://github.com/ros2/yaml_cpp_vendor.git
    version: 7.0.2
  ros\class_loader:
    type: git
    url: https://github.com/ros/class_loader.git
    version: 2.0.2
  ros\kdl_parser:
    type: git
    url: https://github.com/ros/kdl_parser.git
    version: 2.4.1
  ros\pluginlib:
    type: git
    url: https://github.com/ros/pluginlib.git
    version: 0eb530890717c53a29d670b9fd07badbad22b57a
  ros\resource_retriever:
    type: git
    url: https://github.com/ros/resource_retriever.git
    version: 2.3.4
  ros\robot_state_publisher:
    type: git
    url: https://github.com/ros/robot_state_publisher.git
    version: 2.4.2
  ros\ros_environment:
    type: git
    url: https://github.com/ros/ros_environment.git
    version: 2.5.0
  ros\ros_tutorials:
    type: git
    url: https://github.com/ros/ros_tutorials.git
    version: 1fd5ea7c166837ce01a0fb4d00133987ed08d78d
  ros\urdfdom:
    type: git
    url: https://github.com/ros/urdfdom.git
    version: 2.3.3
  ros\urdfdom_headers:
    type: git
    url: https://github.com/ros/urdfdom_headers.git
    version: 8ec38993c21c6913602b9519ca07e4e018af88b5
</pre>
</details>

**Comment by hidmic** [comment]
> @hidmic I have checked locally on Windows, and I have the same test results with this PR and without it.

I see. Let's check again then.

Full Foxy CI, using this branch:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14732/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9483/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12397/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14877/)

and not using this branch:

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14878/)

**Comment by hidmic** [comment]
That test failure does seem unrelated. Let's move forward.

**Pull request merged**
