### PR TITLE
Upgrades to support Fast-RTPS 1.8.0

### PR DESCRIPTION
**Pull request by nburek**
This is a work in progress 

This change is needed for rmw_fastrtps to be compatible with Fast-RTPS 1.8.0

depends on osrf/osrf_testing_tools_cpp#31

### CODE REVIEW

**Comment by nburek** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6768/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3069/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5561/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6593/)

**Comment by dirk-thomas** [comment]
This PR updates the RMW impl. to match the upcoming changes in FastRTPS 1.8 which are currently staged in this PR: eProsima/Fast-RTPS#518

A current round of ROS 2 CI builds with `RelWithDebInfo` seems to fail:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7029/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3264/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5759/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6843/)

@nburek I assume this patch needs to be updated?

**Comment by dirk-thomas** [comment]
@emersonknapp Since you seem to be actively working on this branch can you provide a status for this?

**Comment by emersonknapp** [comment]
@dirk-thomas As it stands this is the final version I want to submit - however I am currently investigating why I am seeing test failures in other parts of the system when using FastRTPS 1.8. Is it ok to open this up for review even though the entire system may not be ok yet? This fixes the build but I am not certain about the functionality. I'm actually not sure - is there a more coordinated effort or group of people I should be looping in to help evaluate the upgrade to 1.8?

**Comment by dirk-thomas** [comment]
> This is now the final version I want to submit for review - it makes the build work against the new FastRTPS 1.8 release branch.

New round of CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7039/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3273/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5768/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6859/)

> Is it ok to open this up for review even though the entire system may not be ok yet?

The current patch looks reasonable to me. My only remark would be that the new function could be implemented in a `.cpp` file instead.

> Is there a more coordinated effort or group of people I should be looping in to help evaluate the upgrade to 1.8?

I guess we won't review any of the changes happening in the FastRTPS repo itself. So this reviewing this patch as well as getting the status of the CI builds to not containany regressions compared to master should be sufficient.

**Comment by dirk-thomas** [comment]
Latest round of CI using this branch and FastRTPS from master:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7075/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3305/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5800/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6893/)

**Comment by dirk-thomas** [comment]
Since the current master fails to build I propose to merge this PR now. The still ongoing CI builds have already passed the package which fails to build on master and is therefore already a significant improvement (independent how many tests are still not passing if any). Any objections?

**Comment by nburek** [comment]
@dirk-thomas Hey dirk, can you make sure that the CI build contains this fix https://github.com/osrf/osrf_testing_tools_cpp/pull/31 to the memory testing tools. 

I'm still seeing some local failures due to timeouts, but I seem to always have timeout failures when running tests on my local machine.

**Comment by dirk-thomas** [comment]
> can you make sure that the CI build contains this fix osrf/osrf_testing_tools_cpp#31 to the memory testing tools.

The builds referenced in my previous comment don't use the fix for `osrf_testing_tools_cpp`. Please start a separate set of builds for that and post them on that PR.

**Comment by emersonknapp** [comment]
No objections from our side on merging now

**Pull request merged**
