### PR TITLE
Perform fault injection in all creation/destruction APIs.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says.

### CODE REVIEW

**Comment by hidmic** [comment]
CI up to `test_rmw_implementation` and `rcl`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12560/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7528/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10271/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12482/)

**Review by brawner — APPROVED** [review]

**Comment by hidmic** [comment]
CI up to `rcutils`, `test_rmw_implementation`, and `rcl`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12569/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7537/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10280/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12492/)

**Comment by hidmic** [comment]
Rebased to bring in #458.

**Comment by hidmic** [comment]
CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12589/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7556/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10301/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12514/)

**Review by brawner — APPROVED** [review]

**Pull request merged**
