### PR TITLE
Add timestamp to rmw_publish tracepoint

### PR DESCRIPTION
**Pull request by cwecht**
Depends on https://github.com/ros2/ros2_tracing/pull/74
For some background: https://github.com/ros2/ros2_tracing/issues/73

Question: Has `write_w_timestamp` + `Time_t::now` any drawbacks if compared with using plain `write`?

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@cwecht Functionally, there are no drawbacks.
Semantically, there might be one issue if we want the tracepoint to be as close to the network/transport as possible (as stated in https://github.com/ros2/ros2_tracing/issues/73#issuecomment-1546273243)

Depending on the QoS settings, there might be a non-negligible blocking of the calling thread before the sample is added to the writer's history. Calling `write` will set `source_timestamp` to the time after that block

**Comment by cwecht** [comment]
I think the proxmity of the tracepoint to the actual write call is not that important in this case, as we can not get any closer to the actual write operation right? For the tracing itself the timestamp passed here is not that important.
For a more precise tracing, adding tracepoints to the DDS implementation itself would be necessary, I suppose, right?

**Comment by MiguelCompany** [comment]
> there is no differing behaviour to be expected, right?

Correct. No differing behaviour other than a different `source_timestamp` being notified on the subscription.

**Review by fujitatomoya — COMMENTED** [review]
lgtm

**Review by fujitatomoya — APPROVED** [review]

**Pull request merged**
