### PR TITLE
address clang nightly build error.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rmw_fastrtps/issues/688

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
I'm not sure, but I don't think this is going to solve the problem.

Under gcc/MSVC, `RCPPUTILS_TSA_GUARDED_BY` is an empty macro.  Under clang, these expand to certain attributes that allow the compiler to trace which locks should be held when accessing these fields (the details are in https://github.com/ros2/rcpputils/blob/rolling/include/rcpputils/thread_safety_annotations.hpp).

All of this infrastructure has been in place since 2019, and used to work.  In point of fact, it seemed to work until last night: the job from [April 17](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1491/) failed, but not because of this issue.

I think something must have changed recently so that the `RCPPUTILS_TSA_GUARDED_BY` macro is no longer doing what we expect, but I'm honestly not sure.  I think it needs a deeper look.

**Comment by iuhilnehc-ynos** [comment]
I can reproduce this issue on my local environment by only compile this source file,

```cpp
clang++ -stdlib=libc++ -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -c custom_participant_info.cpp -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rcutils -I/home/chenlh/Projects/ROS2/ros2-master/install/include -I/home/chenlh/Projects/ROS2/ros2-master/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/include -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rcpputils -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rmw -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rosidl_runtime_c -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rosidl_typesupport_interface -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rosidl_dynamic_typesupport -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rmw_dds_common -I/home/chenlh/Projects/ROS2/ros2-master/install/include/rosidl_runtime_cpp
In file included from custom_participant_info.cpp:26:
In file included from /home/chenlh/Projects/ROS2/ros2-master/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp:46:
/home/chenlh/Projects/ROS2/ros2-master/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_event_info.hpp:81:42: error: expected ';' at end of declaration list
  bool inconsistent_topic_changed_{false}
                                         ^
                                         ;
1 error generated.

```

after using https://github.com/ros2/rmw_fastrtps/pull/689/commits/27cf3737af90923deb960c1ab4e24a377209f91c

```
/home/chenlh/Projects/ROS2/ros2-master/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_event_info.hpp:81:42: error: expected ';' at end of declaration list
  bool inconsistent_topic_changed_{false} RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_);
                                         ^
                                         ;
1 error generated.

```

Maybe we need to update this like

```cpp
  bool inconsistent_topic_changed_
  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_){false};
```
   or
```cpp
  bool inconsistent_topic_changed_
  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_) = false;
```

**Comment by fujitatomoya** [comment]
```bash
  bool inconsistent_topic_changed_
  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_){false};
```

actually i tried this one at 1st, but did not work out...

**Comment by iuhilnehc-ynos** [comment]
> actually i tried this one at 1st, but did not work out...

I tested both, and they worked as I expected.

**Comment by fujitatomoya** [comment]
hmmm, okay let me try that, maybe i got something wrong...

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos it seems to work, probably my environment is not update with rolling head, my bad. i will update the fix.

**Comment by fujitatomoya** [comment]
```cpp
  bool inconsistent_topic_changed_
  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_) {false};
```

generates uncrustify error, which brings back the original issue.

```bash
5: Code style divergence in file 'include/rmw_fastrtps_shared_cpp/custom_event_info.hpp':
5:
5: --- include/rmw_fastrtps_shared_cpp/custom_event_info.hpp
5: +++ include/rmw_fastrtps_shared_cpp/custom_event_info.hpp.uncrustify
5: @@ -82 +82 @@
5: -  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_) {false};
5: +  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_) {false}
5:
5: 1 files with code style divergence
```

but the following works,

```cpp
  bool inconsistent_topic_changed_
  RCPPUTILS_TSA_GUARDED_BY(on_new_event_m_) = false;
```

**Review by fujitatomoya — COMMENTED** [review]
@Yadunund @iuhilnehc-ynos @clalancette i believethis should work.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18595/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13135/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19332/)

**Comment by clalancette** [comment]
Let's also run this on the clang CI job to see what happens.  Note that I expect this job to fail, but not to fail while building `rmw_fastrtps`:

* Clang [Build Status](http://ci.ros2.org/job/ci_linux_clang_libcxx/16/)

**Comment by fujitatomoya** [comment]
@clalancette it seems to be green light on `rmw_fastrtps` with clang build.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
> @clalancette it seems to be green light on `rmw_fastrtps` with clang build.

Yep.  I'll keep this on the list to merge after the Rolling freeze is lifted.

**Review by iuhilnehc-ynos — APPROVED** [review]

**Pull request merged**
